# Generated by Django 5.0.7 on 2024-07-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.TextField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
    ]
